[package]
name = "cc2p"
version = "0.1.5"
edition = "2021"
description = "Convert a CSV to parquet file format"
authors = ["rayyildiz"]
license-file = "LICENSE"
homepage = "https://github.com/rayyildiz/cc2p"
readme = "README.md"

[dependencies]
arrow-csv = { version = "51" }
parquet = { version = "51", features = ["arrow-csv", "arrow"] }
clap = { version = "4.5", features = ["derive", "std"] }
indicatif = { version = "0.17" }
tokio = { version = "1.36", default-features = false, features = ["rt", "rt-multi-thread"] }


[profile.release]
codegen-units = 1
lto = true
panic = "abort"
debug = false
strip = "debuginfo"
opt-level = 3
