[package]
name = "cc2p"
version = "0.2.0"
edition = "2021"
description = "Convert a CSV to parquet file format"
authors = ["rayyildiz"]
license-file = "LICENSE"
repository = "https://github.com/rayyildiz/cc2p"
readme = "README.md"
keywords = ["cli", "ccv", "parquet"]
rust-version = "1.70.0"
categories = ["parsing", "text-processing", "command-line-interface"]

[dependencies]
arrow-csv = { version = "51" }
arrow-schema = { version = "51" }
parquet = { version = "51", features = ["arrow-csv", "arrow"] }
clap = { version = "4.5", features = ["derive", "std"] }
indicatif = { version = "0.17" }
tokio = { version = "1.36", default-features = false, features = ["rt", "rt-multi-thread"] }
regex = { version = "1.5" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
debug = false
strip = "debuginfo"
opt-level = 3
